"""Connector framework: define a connector once, get resumable sync and lease-safe write-backs."""

from elastly.connector.checkpoints import FileCheckpointStore, InMemoryCheckpointStore
from elastly.connector.client import (
    DEFAULT_DRAIN_TIMEOUT_MS,
    DEFAULT_POLL_INTERVAL_MS,
    MAX_RECORDS_PER_CALL,
    DrainTimeoutError,
    ElastlyConnectorClient,
    IngestClient,
    WritebacksClient,
    connector_client,
)
from elastly.connector.ports import (
    INGEST_ENTITIES,
    AckOutcome,
    BatchCreated,
    BatchStatus,
    CheckpointStore,
    CommitResult,
    ConnectorClient,
    ConnectorIngestClient,
    ConnectorWritebacksClient,
    ElastlyConnector,
    IngestEntity,
    Page,
    Record,
    StageResult,
    WritebackResult,
    WritebackTask,
)
from elastly.connector.runtime import (
    BATCH_CHECKPOINT_KEY,
    DEFAULT_FETCH_RETRY_POLICY,
    DEFAULT_LEASE_SAFETY_MS,
    ConnectorDefinition,
    ConnectorRuntimeEvent,
    ConnectorSyncError,
    ConnectorWarning,
    DrainReport,
    FetchRetryPolicy,
    SyncReport,
    define_connector,
)

__all__ = [
    "AckOutcome",
    "BATCH_CHECKPOINT_KEY",
    "BatchCreated",
    "BatchStatus",
    "CheckpointStore",
    "CommitResult",
    "ConnectorClient",
    "ConnectorDefinition",
    "ConnectorIngestClient",
    "ConnectorRuntimeEvent",
    "ConnectorSyncError",
    "ConnectorWarning",
    "ConnectorWritebacksClient",
    "DEFAULT_DRAIN_TIMEOUT_MS",
    "DEFAULT_FETCH_RETRY_POLICY",
    "DEFAULT_LEASE_SAFETY_MS",
    "DEFAULT_POLL_INTERVAL_MS",
    "DrainReport",
    "DrainTimeoutError",
    "ElastlyConnector",
    "ElastlyConnectorClient",
    "FetchRetryPolicy",
    "FileCheckpointStore",
    "INGEST_ENTITIES",
    "IngestClient",
    "IngestEntity",
    "InMemoryCheckpointStore",
    "MAX_RECORDS_PER_CALL",
    "Page",
    "Record",
    "StageResult",
    "SyncReport",
    "WritebackResult",
    "WritebackTask",
    "WritebacksClient",
    "connector_client",
    "define_connector",
]
