# coding: utf-8

"""
    Elastly API

    Elastly public API v1: price serving, canonical ingest, write-back claims and webhooks. Authenticate every request with an API key: Authorization: Bearer elastly_live_...

    The version of the OpenAPI document: 1.0.0
    Contact: support@elastly.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ClaimWritebacksResponseTasksInner(BaseModel):
    """
    ClaimWritebacksResponseTasksInner
    """ # noqa: E501
    id: StrictStr
    product_sku: StrictStr = Field(alias="productSku")
    product_external_id: StrictStr = Field(alias="productExternalId")
    price_cents: Union[StrictFloat, StrictInt] = Field(alias="priceCents")
    currency: StrictStr
    exchange_rate_to_base: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="exchangeRateToBase")
    reason_summary: Optional[StrictStr] = Field(default=None, alias="reasonSummary")
    pricing_decision_id: Optional[StrictStr] = Field(default=None, alias="pricingDecisionId")
    lease_until: StrictStr = Field(alias="leaseUntil")
    target: Dict[str, Any]
    __properties: ClassVar[List[str]] = ["id", "productSku", "productExternalId", "priceCents", "currency", "exchangeRateToBase", "reasonSummary", "pricingDecisionId", "leaseUntil", "target"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClaimWritebacksResponseTasksInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if exchange_rate_to_base (nullable) is None
        # and model_fields_set contains the field
        if self.exchange_rate_to_base is None and "exchange_rate_to_base" in self.model_fields_set:
            _dict['exchangeRateToBase'] = None

        # set to None if reason_summary (nullable) is None
        # and model_fields_set contains the field
        if self.reason_summary is None and "reason_summary" in self.model_fields_set:
            _dict['reasonSummary'] = None

        # set to None if pricing_decision_id (nullable) is None
        # and model_fields_set contains the field
        if self.pricing_decision_id is None and "pricing_decision_id" in self.model_fields_set:
            _dict['pricingDecisionId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClaimWritebacksResponseTasksInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "productSku": obj.get("productSku"),
            "productExternalId": obj.get("productExternalId"),
            "priceCents": obj.get("priceCents"),
            "currency": obj.get("currency"),
            "exchangeRateToBase": obj.get("exchangeRateToBase"),
            "reasonSummary": obj.get("reasonSummary"),
            "pricingDecisionId": obj.get("pricingDecisionId"),
            "leaseUntil": obj.get("leaseUntil"),
            "target": obj.get("target")
        })
        return _obj


