# coding: utf-8

"""
    Elastly API

    Elastly public API v1: price serving, canonical ingest, write-back claims and webhooks. Authenticate every request with an API key: Authorization: Bearer elastly_live_...

    The version of the OpenAPI document: 1.0.0
    Contact: support@elastly.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from elastly.models.prices_response_lines_inner_one_of_explanation import PricesResponseLinesInnerOneOfExplanation
from elastly.models.prices_response_lines_inner_one_of_reason_inner import PricesResponseLinesInnerOneOfReasonInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PricesResponseLinesInnerOneOf(BaseModel):
    """
    PricesResponseLinesInnerOneOf
    """ # noqa: E501
    price_cents: Union[StrictFloat, StrictInt] = Field(alias="priceCents")
    currency: StrictStr
    pricing_decision_id: Optional[StrictStr] = Field(alias="pricingDecisionId")
    reason: List[PricesResponseLinesInnerOneOfReasonInner]
    reason_summary: StrictStr = Field(alias="reasonSummary")
    explanation: PricesResponseLinesInnerOneOfExplanation
    guardrails_applied: List[StrictStr] = Field(alias="guardrailsApplied")
    confidence: StrictStr
    confidence_score: Union[StrictFloat, StrictInt] = Field(alias="confidenceScore")
    ok: StrictBool
    __properties: ClassVar[List[str]] = ["priceCents", "currency", "pricingDecisionId", "reason", "reasonSummary", "explanation", "guardrailsApplied", "confidence", "confidenceScore", "ok"]

    @field_validator('confidence')
    def confidence_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['high', 'medium', 'low']):
            raise ValueError("must be one of enum values ('high', 'medium', 'low')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PricesResponseLinesInnerOneOf from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in reason (list)
        _items = []
        if self.reason:
            for _item_reason in self.reason:
                if _item_reason:
                    _items.append(_item_reason.to_dict())
            _dict['reason'] = _items
        # override the default output from pydantic by calling `to_dict()` of explanation
        if self.explanation:
            _dict['explanation'] = self.explanation.to_dict()
        # set to None if pricing_decision_id (nullable) is None
        # and model_fields_set contains the field
        if self.pricing_decision_id is None and "pricing_decision_id" in self.model_fields_set:
            _dict['pricingDecisionId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PricesResponseLinesInnerOneOf from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "priceCents": obj.get("priceCents"),
            "currency": obj.get("currency"),
            "pricingDecisionId": obj.get("pricingDecisionId"),
            "reason": [PricesResponseLinesInnerOneOfReasonInner.from_dict(_item) for _item in obj["reason"]] if obj.get("reason") is not None else None,
            "reasonSummary": obj.get("reasonSummary"),
            "explanation": PricesResponseLinesInnerOneOfExplanation.from_dict(obj["explanation"]) if obj.get("explanation") is not None else None,
            "guardrailsApplied": obj.get("guardrailsApplied"),
            "confidence": obj.get("confidence"),
            "confidenceScore": obj.get("confidenceScore"),
            "ok": obj.get("ok")
        })
        return _obj


