# coding: utf-8

"""
    Elastly API

    Elastly public API v1: price serving, canonical ingest, write-back claims and webhooks. Authenticate every request with an API key: Authorization: Bearer elastly_live_...

    The version of the OpenAPI document: 1.0.0
    Contact: support@elastly.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Union
from elastly.models.prices_response_lines_inner_one_of_explanation_drivers_inner import PricesResponseLinesInnerOneOfExplanationDriversInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PricesResponseLinesInnerOneOfExplanation(BaseModel):
    """
    PricesResponseLinesInnerOneOfExplanation
    """ # noqa: E501
    short: StrictStr
    drivers: List[PricesResponseLinesInnerOneOfExplanationDriversInner]
    stance: StrictStr
    margin_pct: Union[StrictFloat, StrictInt] = Field(alias="marginPct")
    target_margin_pct: Union[StrictFloat, StrictInt] = Field(alias="targetMarginPct")
    confidence: StrictStr
    __properties: ClassVar[List[str]] = ["short", "drivers", "stance", "marginPct", "targetMarginPct", "confidence"]

    @field_validator('stance')
    def stance_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['hold_firm', 'at_floor', 'held_near_last', 'flexible', 'standard']):
            raise ValueError("must be one of enum values ('hold_firm', 'at_floor', 'held_near_last', 'flexible', 'standard')")
        return value

    @field_validator('confidence')
    def confidence_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['high', 'medium', 'low']):
            raise ValueError("must be one of enum values ('high', 'medium', 'low')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PricesResponseLinesInnerOneOfExplanation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in drivers (list)
        _items = []
        if self.drivers:
            for _item_drivers in self.drivers:
                if _item_drivers:
                    _items.append(_item_drivers.to_dict())
            _dict['drivers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PricesResponseLinesInnerOneOfExplanation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "short": obj.get("short"),
            "drivers": [PricesResponseLinesInnerOneOfExplanationDriversInner.from_dict(_item) for _item in obj["drivers"]] if obj.get("drivers") is not None else None,
            "stance": obj.get("stance"),
            "marginPct": obj.get("marginPct"),
            "targetMarginPct": obj.get("targetMarginPct"),
            "confidence": obj.get("confidence")
        })
        return _obj


