# coding: utf-8

"""
    Elastly API

    Elastly public API v1: price serving, canonical ingest, write-back claims and webhooks. Authenticate every request with an API key: Authorization: Bearer elastly_live_...

    The version of the OpenAPI document: 1.0.0
    Contact: support@elastly.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PricesRequestLinesInner(BaseModel):
    """
    PricesRequestLinesInner
    """ # noqa: E501
    customer_id: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="customerId")
    customer_external_id: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="customerExternalId")
    product_sku: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="productSku")
    product_external_id: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="productExternalId")
    quantity: Optional[Union[Annotated[float, Field(le=1000000, strict=True, gt=0)], Annotated[int, Field(le=1000000, strict=True, gt=0)]]] = 1
    order_value_cents: Optional[Annotated[int, Field(le=1000000000000, strict=True, ge=0)]] = Field(default=None, alias="orderValueCents")
    order_total_quantity: Optional[Annotated[int, Field(le=100000000, strict=True, ge=0)]] = Field(default=None, alias="orderTotalQuantity")
    urgency: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["customerId", "customerExternalId", "productSku", "productExternalId", "quantity", "orderValueCents", "orderTotalQuantity", "urgency"]

    @field_validator('urgency')
    def urgency_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['standard', 'expedited', 'rush']):
            raise ValueError("must be one of enum values ('standard', 'expedited', 'rush')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PricesRequestLinesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PricesRequestLinesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "customerId": obj.get("customerId"),
            "customerExternalId": obj.get("customerExternalId"),
            "productSku": obj.get("productSku"),
            "productExternalId": obj.get("productExternalId"),
            "quantity": obj.get("quantity") if obj.get("quantity") is not None else 1,
            "orderValueCents": obj.get("orderValueCents"),
            "orderTotalQuantity": obj.get("orderTotalQuantity"),
            "urgency": obj.get("urgency")
        })
        return _obj


