# coding: utf-8

"""
    Elastly API

    Elastly public API v1: price serving, canonical ingest, write-back claims and webhooks. Authenticate every request with an API key: Authorization: Bearer elastly_live_...

    The version of the OpenAPI document: 1.0.0
    Contact: support@elastly.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StageRecordsRequestOneOfRecordsInner(BaseModel):
    """
    StageRecordsRequestOneOfRecordsInner
    """ # noqa: E501
    sku: Annotated[str, Field(min_length=1, strict=True)]
    external_id: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="externalId")
    name: StrictStr
    category: StrictStr
    cost_cents: Annotated[int, Field(le=9007199254740991, strict=True, ge=0)] = Field(alias="costCents")
    current_price_cents: Annotated[int, Field(le=9007199254740991, strict=True, ge=0)] = Field(alias="currentPriceCents")
    map_cents: Optional[Annotated[int, Field(le=9007199254740991, strict=True, ge=0)]] = Field(default=None, alias="mapCents")
    floor_cents: Optional[Annotated[int, Field(le=9007199254740991, strict=True, ge=0)]] = Field(default=None, alias="floorCents")
    ceiling_cents: Optional[Annotated[int, Field(le=9007199254740991, strict=True, ge=0)]] = Field(default=None, alias="ceilingCents")
    is_active: Optional[StrictBool] = Field(default=None, alias="isActive")
    in_stock: Optional[StrictBool] = Field(default=None, alias="inStock")
    stock_on_hand: Optional[Annotated[int, Field(le=9007199254740991, strict=True, ge=-9007199254740991)]] = Field(default=None, alias="stockOnHand")
    brand: Optional[StrictStr] = None
    currency: Optional[StrictStr] = None
    attributes: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["sku", "externalId", "name", "category", "costCents", "currentPriceCents", "mapCents", "floorCents", "ceilingCents", "isActive", "inStock", "stockOnHand", "brand", "currency", "attributes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StageRecordsRequestOneOfRecordsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StageRecordsRequestOneOfRecordsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sku": obj.get("sku"),
            "externalId": obj.get("externalId"),
            "name": obj.get("name"),
            "category": obj.get("category"),
            "costCents": obj.get("costCents"),
            "currentPriceCents": obj.get("currentPriceCents"),
            "mapCents": obj.get("mapCents"),
            "floorCents": obj.get("floorCents"),
            "ceilingCents": obj.get("ceilingCents"),
            "isActive": obj.get("isActive"),
            "inStock": obj.get("inStock"),
            "stockOnHand": obj.get("stockOnHand"),
            "brand": obj.get("brand"),
            "currency": obj.get("currency"),
            "attributes": obj.get("attributes")
        })
        return _obj


