# coding: utf-8

"""
    Elastly API

    Elastly public API v1: price serving, canonical ingest, write-back claims and webhooks. Authenticate every request with an API key: Authorization: Bearer elastly_live_...

    The version of the OpenAPI document: 1.0.0
    Contact: support@elastly.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from elastly.models.stage_records_request_one_of3_records_inner_lines_inner import StageRecordsRequestOneOf3RecordsInnerLinesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StageRecordsRequestOneOf3RecordsInner(BaseModel):
    """
    StageRecordsRequestOneOf3RecordsInner
    """ # noqa: E501
    external_id: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="externalId")
    customer_external_id: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, alias="customerExternalId")
    source_quote_external_id: Optional[StrictStr] = Field(default=None, alias="sourceQuoteExternalId")
    currency: StrictStr
    exchange_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="exchangeRate")
    sold_at: datetime = Field(alias="soldAt")
    lines: Annotated[List[StageRecordsRequestOneOf3RecordsInnerLinesInner], Field(min_length=1)]
    __properties: ClassVar[List[str]] = ["externalId", "customerExternalId", "sourceQuoteExternalId", "currency", "exchangeRate", "soldAt", "lines"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StageRecordsRequestOneOf3RecordsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in lines (list)
        _items = []
        if self.lines:
            for _item_lines in self.lines:
                if _item_lines:
                    _items.append(_item_lines.to_dict())
            _dict['lines'] = _items
        # set to None if customer_external_id (nullable) is None
        # and model_fields_set contains the field
        if self.customer_external_id is None and "customer_external_id" in self.model_fields_set:
            _dict['customerExternalId'] = None

        # set to None if exchange_rate (nullable) is None
        # and model_fields_set contains the field
        if self.exchange_rate is None and "exchange_rate" in self.model_fields_set:
            _dict['exchangeRate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StageRecordsRequestOneOf3RecordsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "externalId": obj.get("externalId"),
            "customerExternalId": obj.get("customerExternalId"),
            "sourceQuoteExternalId": obj.get("sourceQuoteExternalId"),
            "currency": obj.get("currency"),
            "exchangeRate": obj.get("exchangeRate"),
            "soldAt": obj.get("soldAt"),
            "lines": [StageRecordsRequestOneOf3RecordsInnerLinesInner.from_dict(_item) for _item in obj["lines"]] if obj.get("lines") is not None else None
        })
        return _obj


