# coding: utf-8

"""
    Elastly API

    Elastly public API v1: price serving, canonical ingest, write-back claims and webhooks. Authenticate every request with an API key: Authorization: Bearer elastly_live_...

    The version of the OpenAPI document: 1.0.0
    Contact: support@elastly.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class StageRecordsRequestOneOf1RecordsInner(BaseModel):
    """
    StageRecordsRequestOneOf1RecordsInner
    """ # noqa: E501
    name: StrictStr
    external_id: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="externalId")
    segment: Optional[StrictStr] = None
    region: Optional[StrictStr] = None
    country: Optional[StrictStr] = None
    credit_terms: Optional[StrictStr] = Field(default=None, alias="creditTerms")
    currency: Optional[StrictStr] = None
    is_active: Optional[StrictBool] = Field(default=None, alias="isActive")
    attributes: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["name", "externalId", "segment", "region", "country", "creditTerms", "currency", "isActive", "attributes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StageRecordsRequestOneOf1RecordsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if region (nullable) is None
        # and model_fields_set contains the field
        if self.region is None and "region" in self.model_fields_set:
            _dict['region'] = None

        # set to None if country (nullable) is None
        # and model_fields_set contains the field
        if self.country is None and "country" in self.model_fields_set:
            _dict['country'] = None

        # set to None if credit_terms (nullable) is None
        # and model_fields_set contains the field
        if self.credit_terms is None and "credit_terms" in self.model_fields_set:
            _dict['creditTerms'] = None

        # set to None if currency (nullable) is None
        # and model_fields_set contains the field
        if self.currency is None and "currency" in self.model_fields_set:
            _dict['currency'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StageRecordsRequestOneOf1RecordsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "externalId": obj.get("externalId"),
            "segment": obj.get("segment"),
            "region": obj.get("region"),
            "country": obj.get("country"),
            "creditTerms": obj.get("creditTerms"),
            "currency": obj.get("currency"),
            "isActive": obj.get("isActive"),
            "attributes": obj.get("attributes")
        })
        return _obj


